/* Signal Archive: lab catalog presents execution classification and safety up front, never an implied shell. */
import Link from "next/link";
import { api, type Lab, type ListResponse } from "../../lib/api";
import { StatusBadge } from "../../components/status-badge";
import { pageMetadata } from "../../lib/metadata";

export const dynamic = "force-dynamic";
export const metadata = pageMetadata("Labs", "Browse documented, guided, and safe executable cybersecurity labs.", "/labs");
export default async function LabsPage() { const data=await api<ListResponse<Lab>>("/labs",{limit:30}).catch(()=>({total:0,items:[],limit:30,offset:0})); return <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><p className="mono text-[10px] tracking-[.16em] text-[var(--copper)]">AUTHORIZED LEARNING LABS</p><h1 className="display mt-2 text-5xl font-bold">Practice inside a visible boundary.</h1><p className="mt-4 max-w-3xl text-muted">The catalog differentiates documentation-only, guided, and approved executable local-fixture labs. Executable does not mean unrestricted: actions remain declared, isolated, and disposable.</p><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.items.map(lab=><Link className="group border hairline bg-white p-5 transition hover:border-[var(--copper)]" href={`/labs/${lab.id}`} key={lab.id}><div className="flex items-center justify-between gap-3"><span className="mono text-[10px] tracking-[.12em] text-[var(--teal)]">{lab.execution_mode}</span>{lab.execution_mode==="executable" && <span className="mono text-[9px] text-[var(--copper)]">LOCAL FIXTURE</span>}</div><h2 className="display mt-4 text-2xl font-bold group-hover:text-[var(--copper)]">{lab.name}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-muted">{lab.description}</p><div className="mt-4 flex flex-wrap gap-2"><StatusBadge status={lab.verification?.status}/><span className="mono text-[10px] text-muted">{lab.difficulty||"unspecified"}</span></div></Link>)}</div></section>; }
