/* Signal Archive: search results remain API-backed, paginated, and explicit about deterministic ranking. */
import { api, type SearchResult } from "../../lib/api";
import { GlobalSearch } from "../../components/global-search";
import { EntityCard } from "../../components/entity-card";
import { pageMetadata } from "../../lib/metadata";

export const dynamic = "force-dynamic";
export const metadata = pageMetadata("Search", "Search deterministic generated cybersecurity knowledge.", "/search");
export default async function SearchPage({ searchParams }: { searchParams: Promise<{q?:string; type?:string; category?:string; page?:string}> }) {
  const params = await searchParams; const q = params.q || ""; const current = Math.max(1, Number(params.page || "1")); const limit = 20;
  const data = q ? await api<{total:number; results:SearchResult[]}>("/search", {q, type:params.type, category:params.category, limit, offset:(current-1)*limit}).catch(() => ({total:0,results:[]})) : {total:0,results:[]};
  return <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><p className="mono text-[10px] tracking-[.16em] text-[var(--copper)]">GLOBAL SEARCH</p><h1 className="display mt-2 text-5xl font-bold">Find the next relevant connection.</h1><div className="mt-7"><GlobalSearch/></div>{q ? <div className="mt-10 grid gap-7 lg:grid-cols-[220px_1fr]"><aside className="border-t-2 border-[var(--copper)] pt-4"><p className="mono text-[10px] tracking-[.14em] text-muted">QUERY</p><p className="mt-2 font-semibold">“{q}”</p><p className="mt-5 text-sm text-muted"><strong>{data.total}</strong> deterministic matches</p><p className="mt-4 text-xs leading-5 text-muted">Results use the repository’s Phase 3 deterministic ranking. No semantic or AI ranking is applied.</p></aside><div><div className="mb-4 flex flex-wrap gap-2"><span className="mono border hairline bg-white px-2 py-1 text-[10px]">page {current}</span>{params.type && <span className="mono border hairline bg-white px-2 py-1 text-[10px]">type: {params.type}</span>}{params.category && <span className="mono border hairline bg-white px-2 py-1 text-[10px]">category: {params.category}</span>}</div>{data.results.length ? <div className="grid gap-4 md:grid-cols-2">{data.results.map(item => <EntityCard entity={item} score={item.score} key={`${item.type}:${item.id}`}/>)}</div> : <div className="border hairline bg-white p-8"><h2 className="display text-2xl">No matching generated records.</h2><p className="mt-2 text-sm text-muted">Try a broader term or remove a filter. Search history stays in this browser only.</p></div>}</div></div> : <div className="mt-10 border hairline bg-white p-8"><h2 className="display text-2xl">Search tools, concepts, vulnerabilities, labs, and learning paths.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Use the search field above or press <kbd className="mono border hairline px-1">⌘K</kbd> from anywhere on the site.</p></div>}</section>;
}
