/* Signal Archive: bounded visual relationship expansion plus an accessible structured list; never renders the full graph. */
"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { apiUrl, entityHref, graphHref, type Entity } from "../lib/api";

export function RelationshipExplorer({ entity }: { entity: Entity }) {
  const [depth, setDepth] = useState(1); const [items, setItems] = useState<Entity[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { let live = true; setLoading(true); fetch(apiUrl(`/knowledge/${entity.id}/related`, { depth, limit: 12 })).then(response => response.json()).then(data => { if (live) setItems(data.related || []); }).catch(() => { if (live) setItems([]); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [entity.id, depth]);
  return <section className="border hairline bg-[var(--ink)] p-5 text-[var(--paper)]" aria-labelledby="related-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="mono text-[10px] tracking-[.16em] text-[var(--copper)]">BOUNDED EXPLORER</p><h2 id="related-title" className="display mt-1 text-2xl">Related knowledge</h2></div><div className="flex items-center gap-3"><label className="mono flex items-center gap-2 text-xs">Depth <select value={depth} onChange={(event) => setDepth(Number(event.target.value))} className="border border-white/20 bg-transparent px-2 py-1 text-white"><option value={1}>1 hop</option><option value={2}>2 hops</option><option value={3}>3 hops</option></select></label><Link className="mono border border-white/25 px-2 py-1 text-[10px] hover:border-[var(--copper)]" href={graphHref(entity, depth)}>Advanced map</Link></div></div><div className="atlas-grid mt-5 grid min-h-36 place-items-center border border-white/10 p-4"><div className="grid w-full grid-cols-2 gap-3 sm:grid-cols-3">{loading ? <p className="col-span-full text-sm text-[var(--mist)]">Expanding the selected relationship boundary…</p> : items.map((item, index) => <Link className="rise border border-white/15 bg-white/5 p-3 transition hover:border-[var(--copper)]" href={entityHref(item)} key={`${item.type}:${item.id}`} style={{ animationDelay:`${index * 40}ms` }}><span className="mono block text-[9px] uppercase text-[var(--teal)]">{item.type}</span><strong className="mt-1 block text-sm">{item.name}</strong><span className="mt-2 block text-[10px] text-[var(--mist)]">{(item as Entity & { relationship?: string }).relationship || "related"}</span></Link>)}</div></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Accessible structured list of related knowledge</caption><thead className="mono text-[10px] uppercase tracking-[.12em] text-[var(--mist)]"><tr><th className="pb-2">Entity</th><th className="pb-2">Type</th><th className="pb-2">Distance</th></tr></thead><tbody>{items.map(item => <tr className="border-t border-white/10" key={`table-${item.type}:${item.id}`}><td className="py-2"><Link className="hover:text-[var(--copper)]" href={entityHref(item)}>{item.name}</Link></td><td className="py-2 text-[var(--mist)]">{item.type}</td><td className="py-2 text-[var(--mist)]">{String((item as Entity & {distance?: number}).distance || 1)}</td></tr>)}</tbody></table></div></section>;
}
