#!/usr/bin/env python3
from pathlib import Path
import argparse, re, sys

ROOT = Path(__file__).resolve().parents[1]

def meta(text):
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    return {k.strip(): v.strip() for k, v in (line.split(":", 1) for line in text[4:end].splitlines() if ":" in line)}

def tools():
    out = []
    for p in sorted((ROOT / "tools").glob("**/*.md")):
        if p.name in {"README.md", "INDEX.md"}: continue
        m = meta(p.read_text(encoding="utf-8"))
        out.append((m.get("name", p.stem), m.get("category", "Unknown"), m.get("difficulty", "Unknown"), m.get("platforms", "Unknown"), m.get("purpose", "See page"), p.relative_to(ROOT / "tools").as_posix()))
    return out

def render(items):
    lines = ["# Cybersecurity Tools Index", "", "Generated by `scripts/generate-index.py`; do not edit manually.", "", "| Tool | Category | Difficulty | Platform | Page |", "| --- | --- | --- | --- | --- |"]
    for name, cat, diff, platforms, purpose, path in sorted(items, key=lambda x: x[0].lower()):
        lines.append(f"| {name} | {cat} | {diff} | {platforms} | [{path}]({path}) |")
    return "\n".join(lines) + "\n"

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true"); args = ap.parse_args()
    target = ROOT / "tools" / "INDEX.md"
    content = render(tools())
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            print(f"{target} is stale; run python3 scripts/generate-index.py")
            return 1
        print("Generated indexes are current.")
        return 0
    target.write_text(content, encoding="utf-8")
    print(f"Wrote {target} with {len(tools())} tool pages.")
    return 0
if __name__ == "__main__": sys.exit(main())
